{% set name = "protolint" %}
{% set version = "0.54.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yoheimuta/protolint/archive/v{{ version }}.tar.gz
  sha256: 3082d88e3c17a88f3001ffc6849eacd9075a0f847ed6339f81e4f80dd0007751

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - protolint --help

about:
  home: https://github.com/yoheimuta/protolint
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A pluggable linter and fixer to enforce Protocol Buffer style and conventions.
  dev_url: https://github.com/yoheimuta/protolint

extra:
  recipe-maintainers:
    - danielnachun
