{% set name = "protolint" %}
{% set version = "0.53.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yoheimuta/protolint/archive/v{{ version }}.tar.gz
  sha256: 96cd7e7c5858956cad9d72a54fbb34890683c3facfe7d6ff5f2a1c008de03b76

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - protolint --help

about:
  home: https://github.com/yoheimuta/protolint
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: A pluggable linter and fixer to enforce Protocol Buffer style and conventions.
  dev_url: https://github.com/yoheimuta/protolint

extra:
  recipe-maintainers:
    - danielnachun
